# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fcc080f964c330b165399d8dac419fa1397a4673abdee40bf93f86ff216c16e417f817176b114aad2713d7f53e8ab22169c5593f3f50ba87db2a5590cc31659

test:
  secret_key_base: 65e1502982b9cbe1ffc35af03c389a35c841386e592e75ab08fdb27bc745ec56604fb8ebaae9a9770e4b6a1e18400c4954115886606ff93a8df092aa42ed8ef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
